---
title: "day2_task"
author: "Jessica French"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

```{r}
expression_a <- expression(x ^ 2)
derivative_a <- deriv(expression_a, "x")
x <- 3

eval(expression_a)
```

```{r}
expression_b <- expression(2 * (3 * a + 2) ^ 4 - 5)
derivative_b <- deriv(expression_b, "a")
a <- 1.2

eval(expression_b)
```

```{r}
expression_c <- expression((-4 * t)/(t ^ 2 + 1) ^ 3)
derivative_c <- deriv(expression_c, "t")
t <- 0

eval(expression_c)
```

```{r}
penguin_bill_length_depth_plot <- ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Bill Length (mm)", 
       y = "Bill Depth (mm)") +
  ggtitle("Penguin Bill Length vs Depth")

penguin_bill_length_depth_plot
  
```

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species)) +
  ggtitle("Flipper Length by Species") +
  labs(x = "Species", 
       y = "Flipper Length (mm)")
```


